---
- name: LEADER Install necessary packages
  ansible.builtin.package:
    name: 
      - git
      - acl
    state: latest
    update_cache: true

- name: ensure cribl directory exists
  file:
    path: /opt/cribl
    state: directory

- name: user cribl present
  ansible.builtin.user:
    name: cribl
    state: "present"
    shell: "/bin/bash"
    system: true
    create_home: true
    home: "/home/cribl"
    comment: "Cribl Service account"

- name: Create group
  group:
    name: "cribl"
    state: present

- name: Download and decompress Stream
  unarchive:
    src: "{{ lookup('url', 'https://cdn.cribl.io/dl/latest') }}"
    dest: /opt/cribl/
    mode: 0755
    remote_src: yes
    owner: root
    group: root
    # creates: /opt/cribl
    extra_opts: [--strip-components=1]

- name: Leader Mode
  shell:
    cmd: sudo /opt/cribl/bin/cribl mode-master -u secret_token

- name: check folder
  shell:
    cmd: sudo mkdir -p /opt/cribl/local/cribl/auth

- name: change user
  shell:
    cmd: |
      cat > /opt/cribl/local/cribl/auth/676f6174733432.dat <<EOF
      {"it":$(date +%s),"phf":0,"guid":"$(uuidgen)","email":"ccruzb@cribl.io"}
      EOF
  args:
    executable: /bin/bash  

- name: change pass
  shell:
    cmd: |
     cat  > /opt/cribl/local/cribl/auth/users.json <<EOF  
     {"username":"admin","first":"admin","last":"admin","email":"admin","roles":["admin"],"password":"passtest"}
     EOF
  args:
    executable: /bin/bash

- name: Set ownership on the cribl directory again
  ansible.builtin.file:
    path: /opt/cribl
    owner: cribl
    group: cribl
    recurse: yes
    state: directory

- name: Check if cribl.service is present on the host
  stat:
    path: "/etc/systemd/system/cribl.service"
  register: criblservice

- name: Delete cribl.service from previous deployment
  ansible.builtin.command:  sudo rm -f /etc/systemd/system/cribl.service
  when: criblservice.stat.exists

- name: Enable Boot Start
  ansible.builtin.command:
    cmd: /opt/cribl/bin/cribl boot-start enable -u cribl -m systemd

- name: Set ownership on the cribl directory again
  ansible.builtin.file:
    path: /opt/cribl
    owner: cribl
    group: cribl
    recurse: yes
    state: directory

- name: Enable the Cribl service
  ansible.builtin.systemd:
    name: cribl
    enabled: true
    masked: no

- name: Start the Cribl service
  ansible.builtin.systemd:
    name: cribl
    state: started

### Config Leader 
- name: Sleep for 20 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 30
  
- name: Copy license to Leader
  become: true 
  copy:
    src: files/LicenseKey.yml
    dest: /opt/cribl/local/cribl/licenses.yml
    owner: cribl
    group: cribl
    mode: 0644

- name: Template configs to out
  template:
    src: files/out.yaml.j2
    dest: /opt/cribl/groups/default/local/cribl/outputs.yml

- name: Set ownership on the cribl directory again
  ansible.builtin.file:
    path: /opt/cribl
    owner: cribl
    group: cribl
    recurse: yes
    state: directory
       
- name: Push config to worker groups
  ansible.builtin.command: "{{ item }}"
  with_items:
    - /opt/cribl/bin/cribl auth login
    - /opt/cribl/bin/cribl git commit-deploy -g default -m "First commit/deploy - outputs"
  become: yes
  become_user: cribl
  environment:
    CRIBL_USERNAME: admin
    CRIBL_PASSWORD: "{{ tf_cribl_pass }}"
    CRIBL_HOST: http://localhost:9000

- name: Start the Cribl service
  ansible.builtin.systemd:
      name: cribl
      state: restarted