---
- name: Wait 30 seconds, but only start checking after 15 seconds
  wait_for_connection:
    delay: 30
    timeout: 40

- name: Install apt-transport-https
  ansible.builtin.apt:
    name:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
      - rsyslog
    
    state: latest
    update_cache: true

- name: Add signing key for Docker
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Apt update
  ansible.builtin.shell:
    cmd: sudo apt update

- name: Install Docker
  ansible.builtin.apt:
    name:
      - python3-pip
      - docker
      - docker.io
      - docker-compose
      - docker-registry
     
    state: latest
    update_cache: true

- name: Docker permissions
  ansible.builtin.shell:
    cmd: sudo chmod 666 /var/run/docker.sock

- name: Add CPG key for Ctop
  ansible.builtin.shell:
    cmd: sudo wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -

- name: Add Azlux Repository for Ctop
  ansible.builtin.shell:
    cmd: sudo echo "deb http://packages.azlux.fr/debian/ stable main" | sudo tee /etc/apt/sources.list.d/azlux.list


- name: Apt update
  ansible.builtin.shell:
    cmd: sudo apt update

- name: Install Docker CTOP
  ansible.builtin.apt:
    name:
      - docker-ctop