---
- name: Wait 30 seconds, but only start checking after 30 seconds
  wait_for_connection:
    delay: 10
    timeout: 30

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: povadmin
    group: povadmin
    mode: 0775
  loop:
    - /home/povadmin/elk

- name: copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /home/povadmin/elk/{{ item }}
  loop:
   - docker-compose.yml
   - .env

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /home/povadmin/elk/
    files:
    - docker-compose.yml