---
- name: ensure cribl directory exists
  file:
    path: /opt/cribl
    state: directory

- name: user cribl present
  ansible.builtin.user:
    name: cribl
    state: "present"
    shell: "/bin/bash"
    system: true
    create_home: true
    home: "/home/cribl"
    comment: "Cribl Service account"

- name: Create group
  group:
    name: "cribl"
    state: present

- name: Download and decompress Stream
  unarchive:
    src: "{{ lookup('url', 'https://cdn.cribl.io/dl/latest') }}"
    dest: /opt/cribl/
    mode: 0755
    remote_src: yes
    owner: root
    group: root
    # creates: /opt/cribl
    extra_opts: [--strip-components=1]


- name: connect to leader
  shell:
    cmd: sudo /opt/cribl/bin/cribl mode-master -u secret_token

- name: Permissions
  shell:
    cmd: sudo chown -R cribl:cribl /opt/cribl

- name: Enable Boot Start
  shell:
    cmd: sudo /opt/cribl/bin/cribl boot-start enable -u cribl -m systemd   

- name: Permissions
  shell:
    cmd: sudo chown -R cribl:cribl /opt/cribl

- name: Systemctl
  shell:
    cmd: sudo systemctl enable cribl

# Pause for 5 secs to build app cache.
- pause:
    seconds: 5

- name: Systemctl
  shell:
    cmd: sudo systemctl start cribl
